{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "260fd65f-d979-43d7-9c01-d1868436de0f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "import re\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pypdf import PdfReader\n",
    "from sentence_transformers import SentenceTransformer\n",
    "\n",
    "BASE_DIR = Path(__file__).resolve().parent.parent\n",
    "DOCUMENTS_DIR = BASE_DIR / \"data\" / \"documents\"\n",
    "PROCESSED_DIR = BASE_DIR / \"data\" / \"processed\"\n",
    "\n",
    "CHUNKS_PATH = PROCESSED_DIR / \"annual_reports_chunks.csv\"\n",
    "EMBEDDINGS_PATH = PROCESSED_DIR / \"annual_reports_embeddings.npy\"\n",
    "\n",
    "CHUNK_SIZE = 1500\n",
    "OVERLAP = 200\n",
    "MODEL_NAME = \"all-MiniLM-L6-v2\"\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    text = str(text or \"\")\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "    return text.strip()\n",
    "\n",
    "\n",
    "def detect_year(filename):\n",
    "    match = re.search(r\"(19|20)\\d{2}\", filename)\n",
    "    return match.group(0) if match else \"Unknown\"\n",
    "\n",
    "\n",
    "def chunk_text(text, chunk_size=CHUNK_SIZE, overlap=OVERLAP):\n",
    "    text = clean_text(text)\n",
    "\n",
    "    if not text:\n",
    "        return []\n",
    "\n",
    "    chunks = []\n",
    "    start = 0\n",
    "\n",
    "    while start < len(text):\n",
    "        end = min(start + chunk_size, len(text))\n",
    "        chunk = text[start:end].strip()\n",
    "\n",
    "        if chunk:\n",
    "            chunks.append(chunk)\n",
    "\n",
    "        if end >= len(text):\n",
    "            break\n",
    "\n",
    "        start = max(end - overlap, start + 1)\n",
    "\n",
    "    return chunks\n",
    "\n",
    "\n",
    "def process_documents():\n",
    "    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "    pdf_files = sorted(DOCUMENTS_DIR.glob(\"*.pdf\"))\n",
    "\n",
    "    if not pdf_files:\n",
    "        raise FileNotFoundError(\n",
    "            f\"No PDF files found in: {DOCUMENTS_DIR}\"\n",
    "        )\n",
    "\n",
    "    records = []\n",
    "\n",
    "    for pdf_path in pdf_files:\n",
    "        print(f\"\\nProcessing: {pdf_path.name}\")\n",
    "\n",
    "        year = detect_year(pdf_path.name)\n",
    "\n",
    "        reader = PdfReader(str(pdf_path))\n",
    "\n",
    "        for page_number, page in enumerate(reader.pages, start=1):\n",
    "            text = clean_text(page.extract_text())\n",
    "\n",
    "            if not text:\n",
    "                continue\n",
    "\n",
    "            page_chunks = chunk_text(text)\n",
    "\n",
    "            for chunk_number, chunk in enumerate(page_chunks, start=1):\n",
    "                records.append({\n",
    "                    \"document\": pdf_path.name,\n",
    "                    \"year\": year,\n",
    "                    \"page\": page_number,\n",
    "                    \"chunk\": chunk_number,\n",
    "                    \"text\": chunk\n",
    "                })\n",
    "\n",
    "        print(f\"Pages: {len(reader.pages)}\")\n",
    "\n",
    "    if not records:\n",
    "        raise ValueError(\n",
    "            \"No readable text was extracted from the PDF files.\"\n",
    "        )\n",
    "\n",
    "    chunks_df = pd.DataFrame(records)\n",
    "\n",
    "    print(\"\\nCreating embeddings...\")\n",
    "    model = SentenceTransformer(MODEL_NAME)\n",
    "\n",
    "    embeddings = model.encode(\n",
    "        chunks_df[\"text\"].tolist(),\n",
    "        batch_size=32,\n",
    "        show_progress_bar=True,\n",
    "        convert_to_numpy=True,\n",
    "        normalize_embeddings=True\n",
    "    )\n",
    "\n",
    "    chunks_df.to_csv(\n",
    "        CHUNKS_PATH,\n",
    "        index=False,\n",
    "        encoding=\"utf-8\"\n",
    "    )\n",
    "\n",
    "    np.save(\n",
    "        EMBEDDINGS_PATH,\n",
    "        embeddings\n",
    "    )\n",
    "\n",
    "    print(\"\\nCompleted successfully.\")\n",
    "    print(f\"Documents: {chunks_df['document'].nunique():,}\")\n",
    "    print(f\"Chunks: {len(chunks_df):,}\")\n",
    "    print(f\"CSV: {CHUNKS_PATH}\")\n",
    "    print(f\"Embeddings: {EMBEDDINGS_PATH}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    process_documents()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (financial-ai)",
   "language": "python",
   "name": "financial-ai"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
